credentials:
  usernames:
    admin:
      email: admin@exemplo.com
      name: Admin
      password: "12345"

cookie:
  name: streamlit_auth
  key: chave_unica_aleatoria # troque por qualquer string diferente quando quiser invalidar tudo
  expiry_days: 0             # 0 = não persiste sessão, sempre pede login
